### ISSUE TITLE
Use in webpack

### ISSUE THREAD

**Issue by miracle2k** [outpunk/postcss-modules#19]
The postcss readme suggest I can replace the webpack "css modules" loader with `postcss-modules`:

https://github.com/postcss/postcss-loader#integration-with-css-modules

But how exactly? A primitive approach:

```
postcss: function () {
    return [require('postcss-modules')];
}
```

causes .json files to be written out. I need the JSON to be returned to the require() statement though.

**Comment by outpunk** [comment]
You can just use the `getJSON` callback:
```js
postcss([
  require('postcss-modules')({
    getJSON: function(cssFileName, json) {
      var path          = require('path');
      var cssName       = path.basename(cssFileName, '.css');
      var jsonFileName  = path.resolve('./build' + cssName + '.json');
      fs.writeFileSync(jsonFileName, JSON.stringify(json));
    }
  });
]);
```

**Comment by miracle2k** [comment]
I saw this in the README, but this just seems to write the JSON files into a custom path.. What the documentation doesn't explain is how I can make the ``require()`` call in my JavaScript return that JSON, that is, webpack should bundle both the JSON and the CSS. I'm not sure what's going on inside webpack at this point, but the default css modules loader does the right thing.

**Comment by outpunk** [comment]
If you're using CSS Modules only for the client javascript, it's likely you have to use css-loader instead of postcss-modules. The postcss-modules plugin is designated to use CSS Modules with static websites or with server-side frameworks. 

There can be two usecases with webpack: you're building a standalone SPA and you're building assets to use them on the server side. In the first case, it's much better to use just css-loader. In the second case, you have to use css-loader (for client-side things) along with postcss-modules (for server-side).

**Comment by outpunk** [comment]
@miracle2k if you have any more questions, feel free to ask :) And thank you for the feedback!

**Comment by sepo-one** [comment]
that's said :cry: 
i'd rather use postcss/* tools only than in combination with css-loader.

don't understand what's the issue though.
seems like there should a natural way to use postcss-loader in couple with postcss-modules

**Comment by gajus** [comment]
Thats a bummer.

What does css-loader do that postcss-loader cannot replicate (or does not want to replicate)?
